name: Publish Workflow
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Build, bump & publish to npm
    runs-on: ubuntu-latest
    container: httptoolkit/act-build-base:v3.0.0
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          token: ${{ secrets.PAT }}

      - run: npm ci

      # Check that the tests and overall build all still pass:
      - run: npm test
      - run: npm run build

      # Create the new release:
      - name: Bump version & push
        run: |
          git config --global user.name 'EzequielZK'
          git config --global user.email 'EzequielZK@users.noreply.github.com'
          npm version patch
          git push && git push --tags
      # Publish the release to npm:
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
